FROM python:3.10.9

WORKDIR /bot

# Копируем файлы бота
COPY ./bot_drf /bot_drf
COPY requirements.txt ./
# Устанавливаем зависимости
RUN pip install -r requirements.txt


CMD ["python", "bot.py"]
