FROM python:3.10.9

WORKDIR /app

# Копируем файлы проекта Django
COPY ./taskmanager /taskmanager
COPY requirements.txt ./
# Устанавливаем зависимости
RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]