version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tz_lz_db
      POSTGRES_USER: tz_lz_admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./taskmanager:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://tz_lz_admin:1234@db/tz_lz_db

  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    volumes:
      - ./bot_drf:/bot
    depends_on:
      - db
    env_file: .env
    environment:
      - DATABASE_URL=DATABASE_URL=postgres://tz_lz_admin:1234@db/tz_lz_db
      - BOT_TOKEN=${TOKEN}

volumes:
  postgres_data: